# Generated by Django 5.2.4 on 2025-08-30 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starter_page', '0003_article_delete_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('content', models.TextField()),
            ],
        ),
    ]
